-- 授予当前数据库中所有现有schema的权限
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE CURRENT_DATABASE() TO jtdt;

-- 授予当前数据库中所有现有表的权限
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO jtdt;

-- 为未来创建的对象设置默认权限
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO jtdt;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON SEQUENCES TO jtdt;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON FUNCTIONS TO jtdt;

-- 如果有其他schema，也需要为它们设置默认权限
-- 替换 'other_schema' 为实际的schema名称
-- ALTER DEFAULT PRIVILEGES IN SCHEMA other_schema
-- GRANT ALL PRIVILEGES ON TABLES TO jtdt;

-- 确保jtdt用户有连接到该数据库的权限
GRANT CONNECT ON DATABASE CURRENT_DATABASE() TO jtdt;
