-- 将m910b的角色权限授予jtdt
GRANT m910b TO jtdt;

-- 授予所有数据库的权限
GRANT ALL PRIVILEGES ON DATABASE your_database_name TO jtdt;

-- 连接到特定数据库
\c your_database_name

-- 授予所有模式的权限
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE your_database_name TO jtdt;

-- 授予所有表的权限
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO jtdt;

-- 为未来创建的对象设置默认权限
ALTER DEFAULT PRIVILEGES FOR USER m910b IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO jtdt;

ALTER DEFAULT PRIVILEGES FOR USER m910b IN SCHEMA public
GRANT ALL PRIVILEGES ON SEQUENCES TO jtdt;

ALTER DEFAULT PRIVILEGES FOR USER m910b IN SCHEMA public
GRANT ALL PRIVILEGES ON FUNCTIONS TO jtdt;

-- 刷新权限
REASSIGN OWNED BY m910b TO jtdt;
